const SET_BITSO_CRYPTO_DATA = 'SET_BITSO_CRYPTO_DATA';
const SET_COINCAP_CRYPTO_DATA = 'SET_COINCAP_CRYPTO_DATA';
const SET_COINLORE_CRYPTO_DATA = 'SET_COINLORE_CRYPTO_DATA';
const FETCH_ALL_DATA = 'FETCH_ALL_DATA';
const SET_CURRENT_CRYPTO = 'SET_CURRENT_CRYPTO';
const SET_UPDATED = 'SET_UPDATED';
export {
  SET_BITSO_CRYPTO_DATA,
  SET_COINCAP_CRYPTO_DATA,
  SET_COINLORE_CRYPTO_DATA,
  FETCH_ALL_DATA,
  SET_CURRENT_CRYPTO,
  SET_UPDATED
};
